Add GraphiQL route to app to let users experiment with test queries
relayjs/relay-examples pull request #273
Opened 2023-01-13 17:57 UTC by ernieturner

Adds the GraphiQL playground UI to the `/playground` route when running the `newsfeed` app locally. Nothing fancy so far with plugins or anything, but works well in terms of pulling schema docs.

![Screenshot 2023-01-13 at 10 56 37 AM](https://user-images.githubusercontent.com/11216295/212387962-e32b9549-7f6e-4a99-8a9e-f017b203342b.png)

2023-01-13 17:58 UTC, ernieturner commented
@davidmccabe Just a heads up about this addition

2023-01-13 18:15 UTC, sibelius approved these changes

2023-01-17 00:42 UTC, alunyov requested changes
This is great!
Thanks @ernieturner for adding this so quickly!

Overall, looks good - one small question about the `regenerator-runtime/runtime.js`. I think we are using webpack for the example, and it should be able to compile graphiql without any additional runtimes. But I'm missing something...

2023-01-17 00:42 UTC, alunyov commented on newsfeed/src/components/playground/GraphiQL.tsx
> +import "regenerator-runtime/runtime.js";
hmm, why do we need this?

2023-01-17 16:55 UTC, ernieturner commented on newsfeed/src/components/playground/GraphiQL.tsx
> +import "regenerator-runtime/runtime.js";
Good catch, removed. I think this just got added when I was copying in some GraphiQL examples.

2023-01-17 16:56 UTC, alunyov approved these changes

2023-01-20 12:46 UTC, vit0rr approved these changes

2023-01-25 04:27 UTC, merged